# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sandeep Suman
email: sandeep@infimath.com
description: >- # this means to ignore newlines until "baseurl:"
  This website contain the work and hobby of sandeep suman.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ssmodev.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

remote_theme: "mmistakes/so-simple-theme"
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
mathjax: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

footer_links:
  - title: Twitter
    url: https://twitter.com/ssumanss
    icon: fab fa-twitter-square
  - title: Facebook
    url: https://facebook.com/ssumanmath
    icon: fab fa-facebook-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
    
copyright: "This site is made with <3 by *me, myself, and I*."    
